# Build settings

markdown: kramdown
plugins:             [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

port: 4000

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		           "Johannes J. Müller"
description:	       "Powered by Jekyll and GitHub Pages"
author:              "Johannes J. Müller"
